### ISSUE TITLE
idea tracker 2: architecture nightmare boogaloo

### ISSUE THREAD

**Issue by SEAPUNK** [SEAPUNK/jobber#10]
Things to keep in mind when building this thing:
- [ ] **THE ~~SERVER~~ STORE IS THE SOURCE OF TRUTH AND ATOMIC OPERATIONS**
- [ ] **~~THE STORE IS JUST A PERSISTENCE LAYER~~**
- [ ] All-atomic operations where it counts
- [x] Server API architecture: #7
- [ ] Fault tolerance: #9
- [ ] Server listeners (external APIs): #10
- [ ] How the runner "registers" its runs: #8
- [x] _XBPF requirement_ Merging of jobs: #4
- [ ] Alternative job data formats: #3
- [ ] Timeouts: #12 
- [x] Job ID generation: #1

**Comment by SEAPUNK** [comment]
- **Job is one task, it will only ever have one runner at the same time.**

**Comment by SEAPUNK** [comment]
- **Multiple servers is long term. You can have a separate project to think of that kind of stuff.**

**Comment by SEAPUNK** [comment]
- **Design for only one server, and one store at a time, and one API at a time.**
- **APIs to keep in mind while designing: Local, REST, WebSocket**
- **Stores to keep in mind while designing: Memory**

---
- **Don't think about Redis and SQLite stores just yet. You need to get up close and personal with them before using them.**
